refactor claim script

diff --git a/.github/workflows/tests-integration.yml b/.github/workflows/tests-integration.yml
--- a/.github/workflows/tests-integration.yml
+++ b/.github/workflows/tests-integration.yml
@@ -58,13 +58,14 @@ jobs:
           lease_duration:      ${{ vars.SHEPHERD_LEASE_DURATION      || '30m'               }}
           lease_namespace:     ${{ inputs.lease_namespace  || vars.SHEPHERD_LEASE_NAMESPACE || 'tas-devex' }}
           cfd_version:         ${{ inputs.cfd_version      || vars.CFD_VERSION              || 'v29.1.0' }}
+          poll_interval:       ${{ vars.SHEPHERD_POLL_INTERVAL        || '30'               }}
         run: |
           set -eo pipefail
           shepherd login service-account ${account_token}
 
           if [[ -z $SHEPHERD_LEASE_ID ]]; then
             if [ -z "$template_argument" ]; then
-              export template_argument=$(cat <<EOF
+              read -r -d '' template_argument << EOM
           {
             "gcp_region": "us-west2",
             "vm_type": "n1-standard-8",
@@ -73,64 +74,60 @@ jobs:
             "cfd_version": "${cfd_version}",
             "additional_opsfiles_b64": ""
           }
-          EOF
-              )
+          EOM
             fi
 
-            lease_id=$( shepherd create lease                           \
-                        --template-argument  "$template_argument"     \
-                        --template-namespace "${template_namespace}"  \
-                        --template           "${template_name}"       \
-                        --namespace          "${lease_namespace}"     \
-                        --duration           "${lease_duration}"      \
-                        --description "Claimed by CF CLI workflow ${{ github.workflow_run.url }}" \
-                        --json \
-                      | jq -r .id
-                    )
+            lease_id=$( shepherd create lease \
+              --template-argument  "$template_argument" \
+              --template-namespace "${template_namespace}" \
+              --template           "${template_name}" \
+              --namespace          "${lease_namespace}" \
+              --duration           "${lease_duration}" \
+              --description "Claimed by CF CLI workflow ${{ github.workflow_run.url }}" \
+              --json | jq -r .id
+            )
           else
             lease_id=$SHEPHERD_LEASE_ID
           fi
 
           echo "Shepherd lease ID: ${lease_id}"
 
-          # Give sometime for the lease to complete. Shepherd may take upto an 3 hours to create an env
-          # if the pool is empty.
-          count=0
           echo "::group::Waiting for Shepherd environment provisioning"
-          while [ $count -lt 360 ] ; do
-            sleep 30
-            status=$( shepherd get lease ${lease_id} \
-                      --namespace ${lease_namespace} \
-                      --json \
-                    | jq -r .status
-                  )
-            if [ $status == "LEASED" ] ; then
-              shepherd get lease ${lease_id} \
-                --namespace ${lease_namespace} \
-                --json \
-              | jq .output > metadata.json
-              break
-            elif [ $status == "FAILED" -o $status == "EXPIRED" ] ; then
-              echo "Error: Lease status is ${status}"
-              exit 1
-            else
-              echo "Waiting for environment to be ready. Status: ${status}"
-            fi
-            count=$(($count+1))
+          count=0
+          max_attempts=240
+          
+          while [ $count -lt $max_attempts ]; do
+            status=$(shepherd get lease ${lease_id} --namespace ${lease_namespace} --json | jq -r .status)
+            
+            case $status in
+              "LEASED")
+                shepherd get lease ${lease_id} --namespace ${lease_namespace} --json | jq .output > metadata.json
+                break
+                ;;
+              "FAILED"|"EXPIRED")
+                echo "Error: Lease status is ${status}"
+                exit 1
+                ;;
+              *)
+                echo "Waiting for environment to be ready. Status: ${status}"
+                sleep $poll_interval
+                count=$((count + 1))
+                ;;
+            esac
           done
           echo "::endgroup::"
 
-          if [ $count -eq 360 ]; then
+          if [ $count -eq $max_attempts ]; then
             echo "Error: Timeout waiting for environment"
             exit 1
           fi
 
           env_name=$(jq -r .name metadata.json)
-          echo "env name is ${env_name}"
+          echo "Environment name: ${env_name}"
           echo "leaseid=${lease_id}" >> "${GITHUB_OUTPUT}"
 
           cf_deployment_version=$(jq -r .cf_deployment_version metadata.json)
-          echo "cf_deployment_version is ${cf_deployment_version}"
+          echo "CF Deployment version: ${cf_deployment_version}"
           echo "cf_deployment_version=${cf_deployment_version}" >> "${GITHUB_OUTPUT}"
 
           environment_metadata=$(jq -r . metadata.json)
